### ISSUE TITLE
Criar ambiente de documentação - Github Pages

### ISSUE THREAD

**Issue by durvalcarvalho** [Requisitos-de-Software/2020.2-Grupo8#3]
### Descrição:

Criação de ambiente com Github Pages para registrar documentos do projeto. A pessoa que for fazer essa issue deve deixar documentado nos comentários como adicionar novos documentos e como rodar o framework utilizado localmente.

### Critérios de aceitação:

- Deve ser acessível pelo link do Github IO.

### Tarefas:

- [x] Criar Github Pages
- [x] Documentar utilização

**Comment by LeoSilvaGomes** [comment]
`Refatore issue mediante a decisão feita`

Não houve necessidade de refatoração na issue, o professor tornou público o repositório do grupo
